### PR TITLE
/units function to display a table with a given players Units.

### PR DESCRIPTION
**Pull request by Whitehowle**
This is related to issue #28, I'm not sure if this is what you had in mind here and I'm also a little wary of the way I format this data to display to the user but I couldn't find an example where we had displayed data before.

### CODE REVIEW

**Review by CheesiestMaster — CHANGES_REQUESTED** [review]
you need to do justification if you are going to display that style of table, which requires prechecking the data to find the widths of each column

**Comment by Whitehowle** [comment]
Do you have a better recommendation for displaying the data? I suspect this isn't the best way to deal with the data, especially with the Name column being up to 200+ characters potentially. Seems a bit brute forced this way.

**Comment by CheesiestMaster** [comment]
Names will be capped at 30?, just do {name} ({type}) "{callsign if unit.status == ACTIVE else ""}" {status}

**Comment by nweissoertel** [comment]
Also shouldn't it be filtered by unit type and ao?
because just a list of ALL units isn't that helpful, the original intention was to find a unit by it's type for something like evac

**Review by CheesiestMaster — APPROVED** [review]

**Pull request merged**
